<?
/**
 * @var \advertisement_model[] $banners
 * @var string                 $order
 */
if ($order == 'V') {
    $col = 12;
} else {
    $col = 12 / count($banners);
}
if ($col == 12) {
    foreach ($banners as $key => $banner) {
        echo image::getBannerHtml($banner);
    }
} else {
    ?>
    <div class="row">
    <? foreach ($banners as $key => $banner) { ?>
        <div class="col-md-<?= $col ?>">
            <?= image::getBannerHtml($banner) ?>
        </div>
    <? } ?>
    </div><?
}
